version: '3.8'

services:
  segmentation:
    build: .
    container_name: sam-segmentation
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models:ro
      - ./main.py:/app/main.py:ro
    environment:
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      - HIP_VISIBLE_DEVICES=0
      - ROCR_VISIBLE_DEVICES=0
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
      - render
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s